version: "2.0"

services:

  external-envoy:
    build:
      context: .
      dockerfile: Dockerfile-external-envoy
    volumes:
      - ./external-envoy.yaml:/etc/external-envoy.yaml
    networks:
      - envoymesh
    expose:
      - "80"
      - "8001"
    ports:
      - "80:80"
      - "8001:8001"

  sa-frontend:
    build: 
      context: ./sa-frontend
    image: rinormaloku/sentiment-analysis-frontend:feedback
    networks:
      envoymesh:
        aliases:
          - sa-frontend
    expose:
      - "80"

  sa-webapp:
    build: 
      context: ./sa-webapp
    image: rinormaloku/sentiment-analysis-web-app:feedback
    networks:
      envoymesh:
        aliases:
          - sa-webapp
    expose:
      - "8080"
    environment:
    - SA_LOGIC_API_URL=http://sa-logic:5000

  sa-logic:
    build:
      context: ./sa-logic
    image: rinormaloku/sentiment-analysis-logic:feedback
    networks:
      envoymesh:
        aliases:
          - sa-logic
    expose:
      - "5000"


  sa-feedback:
    build:
      context: ./sa-feedback
    image: rinormaloku/sentiment-analysis-feedback:feedback
    networks:
      envoymesh:
        aliases:
          - sa-feedback
    expose:
      - "80"
    environment:
    - DATABASE_DIR=/usr/db
    volumes:
     - "./sa-feedback/Database:/usr/db"

networks:
  envoymesh: {}