// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SA.Feedback.Model;

namespace SA.Feedback.Migrations
{
    [DbContext(typeof(FeedbackContext))]
    [Migration("20181201104824_initialCreate")]
    partial class initialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("SA.Feedback.Model.Feedback", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Correct");

                    b.Property<decimal>("Polarity");

                    b.Property<string>("Sentence");

                    b.HasKey("ID");

                    b.ToTable("Feedback");
                });
#pragma warning restore 612, 618
        }
    }
}
